kind: pipeline
name: default
workspace:
  base: /go
  path: src/github.com/fbbin/demo

steps:
- name: ping
  image: redis
  commands:
  - redis-cli -h cache ping

- name: test
  image: golang
  commands:
  - go get
  - go test
  - go build -o fbbin

- name: publish
  image: plugins/github-release
  settings:
    api_key: xxxxxxxx
      from_secret: 2f677bdf9c0e65209600b2f460c70f032d772569
    files: *
    title: 0.0.1
    checksum:
      - md5
      - sha1
    
services:
- name: cache
  image: redis
