kind: pipeline
name: default
workspace:
  base: /go
  path: src/github.com/fbbin/demo

steps:
- name: ping
  image: redis
  commands:
  - redis-cli -h cache ping

- name: test
  image: golang
  commands:
  - go get
  - go test
  - go build -o fbbin

- name: publish  
  image: plugins/gh-pages
  settings:
    username: fbbin
    password: binbin19891117
    pages_directory: public/
    
services:
- name: cache
  image: redis
