kind: pipeline
name: default
workspace:
  base: /go
  path: src/github.com/fbbin/demo

steps:
- name: ping
  image: redis
  commands:
  - redis-cli -h cache ping
- name: test
  image: golang
  commands:
  - go get
  - go test

services:
- name: cache
  image: redis
