before_script:
  - export GO_PROJECT_NAMESPACE="$GOPATH/src/gitexample.com/$CI_PROJECT_NAMESPACE"
  - echo $GO_PROJECT_NAMESPACE

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo $PATH
  
test:
  stage: test
  script:
    - echo $GOPATH