before_script:
  - export GO_PROJECT_NAMESPACE="$GOPATH/src/gitlab-ci-demo/"
  - echo $GO_PROJECT_NAMESPACE
  - mkdir -p $GO_PROJECT_NAMESPACE
  - cd GO_PROJECT_NAMESPACE

stages:
  - build
  - test

build:
  stage: build
  script:
    - go build
  
test:
  stage: test
  script:
    - go test -v ./...